import dotenv from 'dotenv';
import mongoose from 'mongoose';
import { connectDB, disconnectDB } from './config/db';
import { User } from './models/User';
import { Farm } from './models/Farm';
import { Crop } from './models/Crop';
import { SoilReport } from './models/SoilReport';
import { Weather } from './models/Weather';
import { MarketPrice } from './models/MarketPrice';
import { Product } from './models/Product';
import { Order } from './models/Order';
import { Scheme } from './models/Scheme';
import { Expert } from './models/Expert';
import { Consultation } from './models/Consultation';
import { Article } from './models/Article';
import { Notification } from './models/Notification';
import { Irrigation } from './models/Irrigation';
import { DiseaseReport } from './models/DiseaseReport';

dotenv.config();

export const runSeed = async (disconnectWhenDone = true) => {
  try {
    const isAlreadyConnected = mongoose.connection.readyState === 1;
    if (!isAlreadyConnected) {
      await connectDB();
    }
    console.log('🌱 Checking / Seeding database records for KRISHI DIGITAL...');

    // Clear existing records
    await Promise.all([
      User.deleteMany({}),
      Farm.deleteMany({}),
      Crop.deleteMany({}),
      SoilReport.deleteMany({}),
      Weather.deleteMany({}),
      MarketPrice.deleteMany({}),
      Product.deleteMany({}),
      Order.deleteMany({}),
      Scheme.deleteMany({}),
      Expert.deleteMany({}),
      Consultation.deleteMany({}),
      Article.deleteMany({}),
      Notification.deleteMany({}),
      Irrigation.deleteMany({}),
      DiseaseReport.deleteMany({}),
    ]);
    console.log('🧹 Purged existing collections.');

    // 1. Seed Users (1 Admin + 5 Farmers)
    // NOTE: demo admin credentials for development testing
    const adminUser = await User.create({
      name: 'Krishi Digital Administrator',
      email: 'admin@krishidigital.com',
      mobile: '+91 98765 00000',
      password: 'Admin@123',
      role: 'admin',
      state: 'Gujarat',
      district: 'Gandhinagar',
      village: 'Sector 10',
      landArea: 0,
      primaryCrop: 'Administrative HQ',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    });

    const farmer1 = await User.create({
      name: 'Ramesh Patel',
      email: 'ramesh.farmer@krishidigital.com',
      mobile: '+91 98251 12345',
      password: 'Farmer@123',
      role: 'farmer',
      state: 'Gujarat',
      district: 'Ahmedabad',
      village: 'Sanand',
      landArea: 7.5,
      primaryCrop: 'Cotton',
      avatar: 'https://images.unsplash.com/photo-1595278069441-2cf29f8005a4?auto=format&fit=crop&q=80&w=300',
    });

    const farmer2 = await User.create({
      name: 'Suresh Chaudhary',
      email: 'suresh.chaudhary@krishidigital.com',
      mobile: '+91 94280 23456',
      password: 'Farmer@123',
      role: 'farmer',
      state: 'Gujarat',
      district: 'Mehsana',
      village: 'Visnagar',
      landArea: 5.0,
      primaryCrop: 'Wheat',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    });

    const farmer3 = await User.create({
      name: 'Jayesh Jadeja',
      email: 'jayesh.jadeja@krishidigital.com',
      mobile: '+91 97230 34567',
      password: 'Farmer@123',
      role: 'farmer',
      state: 'Gujarat',
      district: 'Rajkot',
      village: 'Gondal',
      landArea: 12.0,
      primaryCrop: 'Groundnut',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300',
    });

    const farmer4 = await User.create({
      name: 'Bharat Solanki',
      email: 'bharat.solanki@krishidigital.com',
      mobile: '+91 96380 45678',
      password: 'Farmer@123',
      role: 'farmer',
      state: 'Gujarat',
      district: 'Junagadh',
      village: 'Keshod',
      landArea: 4.2,
      primaryCrop: 'Wheat',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=300',
    });

    const farmer5 = await User.create({
      name: 'Dinesh Vaghela',
      email: 'dinesh.vaghela@krishidigital.com',
      mobile: '+91 95120 56789',
      password: 'Farmer@123',
      role: 'farmer',
      state: 'Gujarat',
      district: 'Vadodara',
      village: 'Karjan',
      landArea: 6.8,
      primaryCrop: 'Rice',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=300',
    });

    console.log('✅ Seeded 6 Users (1 Admin + 5 Farmers)');

    // 2. Seed 8 Farms
    const farms = await Farm.insertMany([
      {
        userId: farmer1._id,
        farmName: 'Surya Green Farm - Field 1',
        location: 'Sanand Taluka, Ahmedabad Rural',
        state: 'Gujarat',
        district: 'Ahmedabad',
        village: 'Sanand',
        area: 4.5,
        soilType: 'Black Cotton Soil',
        irrigationType: 'Drip Irrigation',
        waterSource: 'Narmada Canal & Borewell',
        latitude: 22.9868,
        longitude: 72.3787,
        sensorsCount: 4,
      },
      {
        userId: farmer1._id,
        farmName: 'Sardar Agro Plot - Field 2',
        location: 'Bavla Highway, Ahmedabad',
        state: 'Gujarat',
        district: 'Ahmedabad',
        village: 'Bavla',
        area: 3.0,
        soilType: 'Alluvial Loam',
        irrigationType: 'Sprinkler Irrigation',
        waterSource: 'Tube Well',
        latitude: 22.8365,
        longitude: 72.3615,
        sensorsCount: 3,
      },
      {
        userId: farmer2._id,
        farmName: 'Shree Krishna Farm',
        location: 'Kheralu Road, Visnagar',
        state: 'Gujarat',
        district: 'Mehsana',
        village: 'Visnagar',
        area: 5.0,
        soilType: 'Sandy Loam',
        irrigationType: 'Sub-surface Drip',
        waterSource: 'Deep Tube Well',
        latitude: 23.6961,
        longitude: 72.5483,
        sensorsCount: 3,
      },
      {
        userId: farmer3._id,
        farmName: 'Gondal Golden Acres',
        location: 'Bhadar River Basin, Gondal',
        state: 'Gujarat',
        district: 'Rajkot',
        village: 'Gondal',
        area: 8.0,
        soilType: 'Medium Black Clay',
        irrigationType: 'Micro Drip System',
        waterSource: 'Bhadar Dam Canal',
        latitude: 21.9619,
        longitude: 70.7937,
        sensorsCount: 5,
      },
      {
        userId: farmer3._id,
        farmName: 'Saurashtra Organic Orchard',
        location: 'Dhoraji Highway, Rajkot',
        state: 'Gujarat',
        district: 'Rajkot',
        village: 'Virpur',
        area: 4.0,
        soilType: 'Red Loam Soil',
        irrigationType: 'Drip & Rain Gun',
        waterSource: 'Check Dam Pond',
        latitude: 21.8488,
        longitude: 70.7289,
        sensorsCount: 2,
      },
      {
        userId: farmer4._id,
        farmName: 'Gir Somnath Agro Vihar',
        location: 'Near Gir Sanctuary Buffer, Keshod',
        state: 'Gujarat',
        district: 'Junagadh',
        village: 'Keshod',
        area: 4.2,
        soilType: 'Coastal Alluvium & Loam',
        irrigationType: 'Drip Irrigation',
        waterSource: 'Open Well & Solar Pump',
        latitude: 21.3039,
        longitude: 70.2492,
        sensorsCount: 3,
      },
      {
        userId: farmer5._id,
        farmName: 'Narmada Valley Field',
        location: 'Miyagam Karjan Link, Vadodara',
        state: 'Gujarat',
        district: 'Vadodara',
        village: 'Karjan',
        area: 4.0,
        soilType: 'Deep Black Cotton Soil',
        irrigationType: 'Flood / Furrow with Sensor Gate',
        waterSource: 'Canal Lift Irrigation',
        latitude: 22.0461,
        longitude: 73.1235,
        sensorsCount: 3,
      },
      {
        userId: farmer5._id,
        farmName: 'Padra Organic Greens',
        location: 'Padra Road, Vadodara',
        state: 'Gujarat',
        district: 'Vadodara',
        village: 'Padra',
        area: 2.8,
        soilType: 'Sandy Loam',
        irrigationType: 'Drip Irrigation',
        waterSource: 'Community Borewell',
        latitude: 22.2415,
        longitude: 73.0828,
        sensorsCount: 2,
      },
    ]);
    console.log('✅ Seeded 8 Farms');

    // 3. Seed 15 Crops
    const crops = await Crop.insertMany([
      {
        userId: farmer1._id,
        farmId: farms[0]._id,
        cropName: 'Cotton',
        variety: 'Bt Cotton (G.Cot-Hy-12)',
        plantingDate: new Date('2026-06-15'),
        expectedHarvest: new Date('2026-11-20'),
        growthStage: 'Flowering',
        healthScore: 82,
        area: 3.5,
        irrigationRequirement: '600-750 mm (Drip 3x/week)',
        icon: '🌱',
        notes: 'Monitored with digital leaf sensors. Squaring and flowering progressing smoothly.',
      },
      {
        userId: farmer1._id,
        farmId: farms[0]._id,
        cropName: 'Tomato',
        variety: 'Abhinav Hybrid F1',
        plantingDate: new Date('2026-08-01'),
        expectedHarvest: new Date('2026-10-30'),
        growthStage: 'Fruiting',
        healthScore: 88,
        area: 1.0,
        irrigationRequirement: '400-500 mm (Daily Drip)',
        icon: '🍅',
        notes: 'Staked with bamboo trellis. Fruit sizing healthy with zero blossom end rot.',
      },
      {
        userId: farmer1._id,
        farmId: farms[1]._id,
        cropName: 'Wheat',
        variety: 'GW-496 (Lokwan High Yield)',
        plantingDate: new Date('2026-09-10'),
        expectedHarvest: new Date('2027-01-15'),
        growthStage: 'Vegetative',
        healthScore: 91,
        area: 3.0,
        irrigationRequirement: '450-550 mm (Critical at CRI stage)',
        icon: '🌾',
        notes: 'Uniform germination achieved across all 3 acres.',
      },
      {
        userId: farmer2._id,
        farmId: farms[2]._id,
        cropName: 'Wheat',
        variety: 'GW-322 Sharbati Premium',
        plantingDate: new Date('2026-09-05'),
        expectedHarvest: new Date('2027-01-10'),
        growthStage: 'Vegetative',
        healthScore: 89,
        area: 3.5,
        irrigationRequirement: '450 mm',
        icon: '🌾',
        notes: 'First top dressing with neem coated urea completed.',
      },
      {
        userId: farmer2._id,
        farmId: farms[2]._id,
        cropName: 'Potato',
        variety: 'Kufri Pukhraj',
        plantingDate: new Date('2026-08-20'),
        expectedHarvest: new Date('2026-12-05'),
        growthStage: 'Vegetative',
        healthScore: 84,
        area: 1.5,
        irrigationRequirement: '500 mm',
        icon: '🥔',
        notes: 'Ridge earthing up scheduled next week.',
      },
      {
        userId: farmer3._id,
        farmId: farms[3]._id,
        cropName: 'Groundnut',
        variety: 'TG-37A (Spanish Bunch)',
        plantingDate: new Date('2026-06-25'),
        expectedHarvest: new Date('2026-10-25'),
        growthStage: 'Fruiting',
        healthScore: 76,
        area: 5.0,
        irrigationRequirement: '500 mm (Crucial at pegging)',
        icon: '🥜',
        notes: 'Peg formation stage. Gypsum application applied to increase pod filling.',
      },
      {
        userId: farmer3._id,
        farmId: farms[3]._id,
        cropName: 'Cotton',
        variety: 'Shanker-6 Hybrid',
        plantingDate: new Date('2026-06-20'),
        expectedHarvest: new Date('2026-11-28'),
        growthStage: 'Flowering',
        healthScore: 85,
        area: 3.0,
        irrigationRequirement: '650 mm',
        icon: '🌱',
        notes: 'Pheromone traps installed for pink bollworm monitoring.',
      },
      {
        userId: farmer3._id,
        farmId: farms[4]._id,
        cropName: 'Onion',
        variety: 'Agrifound Dark Red',
        plantingDate: new Date('2026-07-15'),
        expectedHarvest: new Date('2026-11-10'),
        growthStage: 'Vegetative',
        healthScore: 87,
        area: 2.0,
        irrigationRequirement: '350 mm',
        icon: '🧅',
        notes: 'Drip fertigation applied twice weekly.',
      },
      {
        userId: farmer3._id,
        farmId: farms[4]._id,
        cropName: 'Maize',
        variety: 'African Tall Fodder / Sweet Corn',
        plantingDate: new Date('2026-07-28'),
        expectedHarvest: new Date('2026-10-18'),
        growthStage: 'Fruiting',
        healthScore: 92,
        area: 2.0,
        irrigationRequirement: '500 mm',
        icon: '🌽',
        notes: 'Cob filling stage; high sugar content recorded.',
      },
      {
        userId: farmer4._id,
        farmId: farms[5]._id,
        cropName: 'Groundnut',
        variety: 'GG-20 (Gujarat Groundnut)',
        plantingDate: new Date('2026-06-18'),
        expectedHarvest: new Date('2026-10-22'),
        growthStage: 'Harvest',
        healthScore: 90,
        area: 2.5,
        irrigationRequirement: '450 mm',
        icon: '🥜',
        notes: 'Harvesting begins this weekend. Moisture content optimal.',
      },
      {
        userId: farmer4._id,
        farmId: farms[5]._id,
        cropName: 'Wheat',
        variety: 'Lok-1 Gujarat Selected',
        plantingDate: new Date('2026-09-12'),
        expectedHarvest: new Date('2027-01-20'),
        growthStage: 'Germination',
        healthScore: 94,
        area: 1.7,
        irrigationRequirement: '450 mm',
        icon: '🌾',
        notes: '98% germination rate achieved with certified seed batch.',
      },
      {
        userId: farmer5._id,
        farmId: farms[6]._id,
        cropName: 'Rice',
        variety: 'Gujarat Rice-17 (Scented Basmati)',
        plantingDate: new Date('2026-07-01'),
        expectedHarvest: new Date('2026-11-05'),
        growthStage: 'Flowering',
        healthScore: 86,
        area: 4.0,
        irrigationRequirement: '1200 mm (Controlled saturation)',
        icon: '🌾',
        notes: 'AWD (Alternate Wetting and Drying) water management applied.',
      },
      {
        userId: farmer5._id,
        farmId: farms[7]._id,
        cropName: 'Tomato',
        variety: 'Pusa Ruby Heirloom',
        plantingDate: new Date('2026-08-10'),
        expectedHarvest: new Date('2026-11-15'),
        growthStage: 'Flowering',
        healthScore: 83,
        area: 1.4,
        irrigationRequirement: '400 mm',
        icon: '🍅',
        notes: 'Organic neem oil spray schedule active.',
      },
      {
        userId: farmer5._id,
        farmId: farms[7]._id,
        cropName: 'Potato',
        variety: 'Chipsona-3 Processing',
        plantingDate: new Date('2026-08-25'),
        expectedHarvest: new Date('2026-12-15'),
        growthStage: 'Vegetative',
        healthScore: 89,
        area: 1.4,
        irrigationRequirement: '500 mm',
        icon: '🥔',
        notes: 'Contact farming contract with local snack processor.',
      },
      {
        userId: farmer2._id,
        farmId: farms[2]._id,
        cropName: 'Cotton',
        variety: 'Bollgard II Hybrid',
        plantingDate: new Date('2026-06-28'),
        expectedHarvest: new Date('2026-11-30'),
        growthStage: 'Flowering',
        healthScore: 81,
        area: 2.0,
        irrigationRequirement: '600 mm',
        icon: '🌱',
        notes: 'Flowering healthy; no sucking pest pressure observed.',
      },
    ]);
    console.log('✅ Seeded 15 Crops');

    // 4. Seed Soil Reports
    await SoilReport.insertMany([
      {
        userId: farmer1._id,
        farmId: farms[0]._id,
        overallScore: 82,
        rating: 'Excellent',
        pH: 6.8,
        nitrogen: 280,
        phosphorus: 42,
        potassium: 310,
        moisture: 68,
        organicCarbon: 0.75,
        electricalConductivity: 0.45,
        recommendations: [
          'Maintain current organic compost application (4-5 tonnes/acre).',
          'Phosphorus levels are in optimal range; avoid unnecessary DAP overdose.',
          'Incorporate green manuring (Sunhemp/Dhaincha) before next Kharif rotation.',
          'Soil moisture retention is high; check drip lines for uniform distribution.',
        ],
      },
      {
        userId: farmer3._id,
        farmId: farms[3]._id,
        overallScore: 78,
        rating: 'Good',
        pH: 7.2,
        nitrogen: 240,
        phosphorus: 38,
        potassium: 290,
        moisture: 62,
        organicCarbon: 0.65,
        electricalConductivity: 0.52,
        recommendations: [
          'Apply farmyard manure (FYM) to improve organic carbon balance above 0.75%.',
          'Add biofertilizers (Rhizobium culture) to enhance natural nitrogen fixation.',
        ],
      },
    ]);

    // 5. Seed Weather
    await Weather.insertMany([
      {
        district: 'Ahmedabad',
        state: 'Gujarat',
        temperature: 31,
        condition: 'Sunny',
        conditionIcon: '☀️',
        humidity: 62,
        windSpeed: 14,
        rainProbability: 20,
        uvIndex: 7,
        sunrise: '06:18 AM',
        sunset: '06:45 PM',
        forecast: [
          { day: 'Mon', date: 'Oct 06', tempMax: 31, tempMin: 22, condition: 'Sunny', icon: '☀️', rainProb: 10 },
          { day: 'Tue', date: 'Oct 07', tempMax: 28, tempMin: 20, condition: 'Rain Showers', icon: '🌧️', rainProb: 75 },
          { day: 'Wed', date: 'Oct 08', tempMax: 30, tempMin: 21, condition: 'Sunny', icon: '☀️', rainProb: 15 },
          { day: 'Thu', date: 'Oct 09', tempMax: 29, tempMin: 21, condition: 'Partly Cloudy', icon: '☁️', rainProb: 30 },
          { day: 'Fri', date: 'Oct 10', tempMax: 32, tempMin: 23, condition: 'Clear', icon: '☀️', rainProb: 5 },
          { day: 'Sat', date: 'Oct 11', tempMax: 27, tempMin: 20, condition: 'Light Rain', icon: '🌧️', rainProb: 60 },
          { day: 'Sun', date: 'Oct 12', tempMax: 30, tempMin: 22, condition: 'Sunny', icon: '☀️', rainProb: 10 },
        ],
        alerts: [
          {
            type: 'warning',
            title: '⚠️ Heavy Rain Alert',
            description: 'Scattered moderate-to-heavy showers predicted for Tuesday afternoon. Secure harvested crops and clear drainage channels.',
            validUntil: 'Tomorrow, 08:00 PM',
          },
          {
            type: 'info',
            title: '☀️ Favorable Spraying Window',
            description: 'Morning wind speeds <12 km/h provide an optimal window for foliar nutrient sprays.',
            validUntil: 'Today, 11:30 AM',
          },
        ],
      },
      {
        district: 'Rajkot',
        state: 'Gujarat',
        temperature: 32,
        condition: 'Clear',
        conditionIcon: '☀️',
        humidity: 58,
        windSpeed: 16,
        rainProbability: 15,
        uvIndex: 8,
        sunrise: '06:22 AM',
        sunset: '06:49 PM',
        forecast: [
          { day: 'Mon', date: 'Oct 06', tempMax: 32, tempMin: 23, condition: 'Clear', icon: '☀️', rainProb: 5 },
          { day: 'Tue', date: 'Oct 07', tempMax: 30, tempMin: 21, condition: 'Cloudy', icon: '☁️', rainProb: 40 },
          { day: 'Wed', date: 'Oct 08', tempMax: 31, tempMin: 22, condition: 'Sunny', icon: '☀️', rainProb: 10 },
          { day: 'Thu', date: 'Oct 09', tempMax: 33, tempMin: 23, condition: 'Sunny', icon: '☀️', rainProb: 10 },
          { day: 'Fri', date: 'Oct 10', tempMax: 33, tempMin: 24, condition: 'Sunny', icon: '☀️', rainProb: 0 },
          { day: 'Sat', date: 'Oct 11', tempMax: 29, tempMin: 21, condition: 'Showers', icon: '🌧️', rainProb: 55 },
          { day: 'Sun', date: 'Oct 12', tempMax: 31, tempMin: 22, condition: 'Clear', icon: '☀️', rainProb: 10 },
        ],
        alerts: [
          {
            type: 'info',
            title: '💨 Strong Coastal Breeze',
            description: 'Wind gusts up to 28 km/h along southern Saurashtra. Anchor greenhouse sheeting.',
            validUntil: 'Wednesday, 06:00 PM',
          },
        ],
      },
    ]);

    // 6. Seed 20 Market Mandi Records
    await MarketPrice.insertMany([
      {
        crop: 'Cotton',
        variety: 'Shanker-6 Medium Staple',
        market: 'Ahmedabad APMC',
        district: 'Ahmedabad',
        state: 'Gujarat',
        minPrice: 6900,
        maxPrice: 7450,
        modalPrice: 7200,
        changePercent: 4.2,
        trend: 'up',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 6900 },
          { date: '4 Days Ago', modalPrice: 7020 },
          { date: '2 Days Ago', modalPrice: 7110 },
          { date: 'Today', modalPrice: 7200 },
        ],
      },
      {
        crop: 'Wheat',
        variety: 'Lokwan GW-496',
        market: 'Ahmedabad APMC',
        district: 'Ahmedabad',
        state: 'Gujarat',
        minPrice: 2300,
        maxPrice: 2550,
        modalPrice: 2450,
        changePercent: 1.8,
        trend: 'up',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 2380 },
          { date: '4 Days Ago', modalPrice: 2410 },
          { date: '2 Days Ago', modalPrice: 2430 },
          { date: 'Today', modalPrice: 2450 },
        ],
      },
      {
        crop: 'Groundnut',
        variety: 'TG-37A Pods',
        market: 'Gondal APMC',
        district: 'Rajkot',
        state: 'Gujarat',
        minPrice: 5800,
        maxPrice: 6300,
        modalPrice: 6100,
        changePercent: -1.2,
        trend: 'down',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 6250 },
          { date: '4 Days Ago', modalPrice: 6200 },
          { date: '2 Days Ago', modalPrice: 6140 },
          { date: 'Today', modalPrice: 6100 },
        ],
      },
      {
        crop: 'Cotton',
        variety: 'Bt Cotton Long Staple',
        market: 'Rajkot APMC',
        district: 'Rajkot',
        state: 'Gujarat',
        minPrice: 7000,
        maxPrice: 7600,
        modalPrice: 7350,
        changePercent: 3.5,
        trend: 'up',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 7100 },
          { date: 'Today', modalPrice: 7350 },
        ],
      },
      {
        crop: 'Cumin (Jeera)',
        variety: 'Unjha Premium Grade A',
        market: 'Unjha APMC',
        district: 'Mehsana',
        state: 'Gujarat',
        minPrice: 24500,
        maxPrice: 28200,
        modalPrice: 26800,
        changePercent: 5.8,
        trend: 'up',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 25100 },
          { date: 'Today', modalPrice: 26800 },
        ],
      },
      {
        crop: 'Mustard (Rai)',
        variety: 'Bold Black',
        market: 'Mehsana APMC',
        district: 'Mehsana',
        state: 'Gujarat',
        minPrice: 5200,
        maxPrice: 5650,
        modalPrice: 5450,
        changePercent: 0.9,
        trend: 'up',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 5400 },
          { date: 'Today', modalPrice: 5450 },
        ],
      },
      {
        crop: 'Castor Seed (Divela)',
        variety: 'Gujarat Castor-7',
        market: 'Patan APMC',
        district: 'Patan',
        state: 'Gujarat',
        minPrice: 5800,
        maxPrice: 6250,
        modalPrice: 6050,
        changePercent: 1.1,
        trend: 'up',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 5980 },
          { date: 'Today', modalPrice: 6050 },
        ],
      },
      {
        crop: 'Rice (Paddy)',
        variety: 'Basmati Sugandha',
        market: 'Vadodara APMC',
        district: 'Vadodara',
        state: 'Gujarat',
        minPrice: 3200,
        maxPrice: 3800,
        modalPrice: 3550,
        changePercent: 2.1,
        trend: 'up',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 3480 },
          { date: 'Today', modalPrice: 3550 },
        ],
      },
      {
        crop: 'Tomato',
        variety: 'Hybrid Red',
        market: 'Surat APMC',
        district: 'Surat',
        state: 'Gujarat',
        minPrice: 1400,
        maxPrice: 2100,
        modalPrice: 1800,
        changePercent: -4.5,
        trend: 'down',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 1950 },
          { date: 'Today', modalPrice: 1800 },
        ],
      },
      {
        crop: 'Onion',
        variety: 'Red Nasik / Mahuva',
        market: 'Mahuva APMC',
        district: 'Bhavnagar',
        state: 'Gujarat',
        minPrice: 1800,
        maxPrice: 2450,
        modalPrice: 2200,
        changePercent: 6.2,
        trend: 'up',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 2050 },
          { date: 'Today', modalPrice: 2200 },
        ],
      },
      {
        crop: 'Potato',
        variety: 'Deesa Jyoti',
        market: 'Deesa APMC',
        district: 'Banaskantha',
        state: 'Gujarat',
        minPrice: 1200,
        maxPrice: 1650,
        modalPrice: 1450,
        changePercent: 0.0,
        trend: 'stable',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 1450 },
          { date: 'Today', modalPrice: 1450 },
        ],
      },
      {
        crop: 'Maize (Makai)',
        variety: 'Yellow Feed Grain',
        market: 'Dahod APMC',
        district: 'Dahod',
        state: 'Gujarat',
        minPrice: 1950,
        maxPrice: 2250,
        modalPrice: 2120,
        changePercent: 1.4,
        trend: 'up',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 2090 },
          { date: 'Today', modalPrice: 2120 },
        ],
      },
      {
        crop: 'Sesame (Til)',
        variety: 'White Bold Export',
        market: 'Amreli APMC',
        district: 'Amreli',
        state: 'Gujarat',
        minPrice: 11500,
        maxPrice: 13200,
        modalPrice: 12400,
        changePercent: 3.1,
        trend: 'up',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 12000 },
          { date: 'Today', modalPrice: 12400 },
        ],
      },
      {
        crop: 'Chilli (Dry Red)',
        variety: 'Guntur Sanam',
        market: 'Gondal APMC',
        district: 'Rajkot',
        state: 'Gujarat',
        minPrice: 15500,
        maxPrice: 19500,
        modalPrice: 17800,
        changePercent: -2.3,
        trend: 'down',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 18200 },
          { date: 'Today', modalPrice: 17800 },
        ],
      },
      {
        crop: 'Chickpea (Chana)',
        variety: 'Desi Brown',
        market: 'Junagadh APMC',
        district: 'Junagadh',
        state: 'Gujarat',
        minPrice: 5100,
        maxPrice: 5700,
        modalPrice: 5400,
        changePercent: 0.5,
        trend: 'stable',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 5370 },
          { date: 'Today', modalPrice: 5400 },
        ],
      },
      {
        crop: 'Soybean',
        variety: 'Yellow JS-335',
        market: 'Indore Central APMC',
        district: 'Indore',
        state: 'Madhya Pradesh',
        minPrice: 4200,
        maxPrice: 4850,
        modalPrice: 4600,
        changePercent: 1.8,
        trend: 'up',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 4520 },
          { date: 'Today', modalPrice: 4600 },
        ],
      },
      {
        crop: 'Garlic (Lasan)',
        variety: 'Ooty / Jamnagar White',
        market: 'Jamnagar APMC',
        district: 'Jamnagar',
        state: 'Gujarat',
        minPrice: 8500,
        maxPrice: 12500,
        modalPrice: 10800,
        changePercent: 7.4,
        trend: 'up',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 10050 },
          { date: 'Today', modalPrice: 10800 },
        ],
      },
      {
        crop: 'Fennel (Variyali)',
        variety: 'Abu Road Green Bold',
        market: 'Unjha APMC',
        district: 'Mehsana',
        state: 'Gujarat',
        minPrice: 13500,
        maxPrice: 16800,
        modalPrice: 15200,
        changePercent: 2.7,
        trend: 'up',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 14800 },
          { date: 'Today', modalPrice: 15200 },
        ],
      },
      {
        crop: 'Banana',
        variety: 'Grand Naine (G9)',
        market: 'Navsari APMC',
        district: 'Navsari',
        state: 'Gujarat',
        minPrice: 1100,
        maxPrice: 1600,
        modalPrice: 1380,
        changePercent: -1.0,
        trend: 'down',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 1400 },
          { date: 'Today', modalPrice: 1380 },
        ],
      },
      {
        crop: 'Pigeon Pea (Tur Dal)',
        variety: 'White Gulbarga / Gujarat Tur',
        market: 'Himmatnagar APMC',
        district: 'Sabarkantha',
        state: 'Gujarat',
        minPrice: 7800,
        maxPrice: 9100,
        modalPrice: 8500,
        changePercent: 3.2,
        trend: 'up',
        priceHistory: [
          { date: '1 Week Ago', modalPrice: 8240 },
          { date: 'Today', modalPrice: 8500 },
        ],
      },
    ]);
    console.log('✅ Seeded 20 Market Mandi Records');

    // 7. Seed 20 Marketplace Products
    await Product.insertMany([
      {
        name: 'Premium Hybrid Cotton Seeds (G.Cot-Hy-12)',
        category: 'Seeds',
        brand: 'Gujarat Agro Seeds Co.',
        price: 1250,
        originalPrice: 1450,
        discountPercentage: 14,
        rating: 4.8,
        reviewsCount: 38,
        image: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb22510?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 120,
        unit: '450g packet with refuge',
        description: 'Certified high-germination Bt cotton seeds engineered for bollworm resistance and high lint turnout.',
        isFeatured: true,
      },
      {
        name: 'Organic Neem Oil Bio-Pesticide (10,000 PPM)',
        category: 'Pest Control',
        brand: 'Krishi Rakshak Bio',
        price: 680,
        originalPrice: 850,
        discountPercentage: 20,
        rating: 4.7,
        reviewsCount: 42,
        image: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 85,
        unit: '1 Litre bottle',
        description: 'Pure cold-pressed Azadirachtin botanical insecticide. Highly effective against aphids, thrips, and whiteflies.',
        isFeatured: true,
      },
      {
        name: '100% Water Soluble NPK 19-19-19 Fertilizer',
        category: 'Fertilizers',
        brand: 'IFFCO Agro Tech',
        price: 1100,
        originalPrice: 1250,
        discountPercentage: 12,
        rating: 4.9,
        reviewsCount: 76,
        image: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 200,
        unit: '25 kg bag',
        description: 'Balanced soluble grade for drip fertigation and foliar application. Rapid nutrient absorption for all vegetative crops.',
        isFeatured: true,
      },
      {
        name: 'Automated Solar Smart Drip Irrigation Controller',
        category: 'Irrigation',
        brand: 'Jain Solar IoT',
        price: 8499,
        originalPrice: 10999,
        discountPercentage: 23,
        rating: 4.9,
        reviewsCount: 19,
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 25,
        unit: '1 IoT Controller + 2 Sensors',
        description: 'Solar powered smart solenoid valve controller. Connects with mobile app to auto-irrigate according to soil moisture.',
        isFeatured: true,
      },
      {
        name: 'High Performance Battery Knapsack Sprayer (16L)',
        category: 'Machinery',
        brand: 'Aspee Agri Tools',
        price: 2850,
        originalPrice: 3400,
        discountPercentage: 16,
        rating: 4.6,
        reviewsCount: 54,
        image: 'https://images.unsplash.com/photo-1590682680695-43b964a3ae17?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 60,
        unit: '16 Litre Tank + 12V 12Ah Battery',
        description: 'Dual pump high pressure battery sprayer with stainless steel extendable lance and four nozzle attachments.',
        isFeatured: true,
      },
      {
        name: 'Certified GW-496 Sharbati Wheat Seeds',
        category: 'Seeds',
        brand: 'Gujarat State Seeds Corp',
        price: 1450,
        originalPrice: 1600,
        discountPercentage: 9,
        rating: 4.8,
        reviewsCount: 31,
        image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 150,
        unit: '40 kg bag',
        description: 'Certified breeder-standard seeds with 99% genetic purity. High yield potential of 50-55 quintals/hectare.',
      },
      {
        name: 'Organic Vermicompost Enricher (Earthworm Castings)',
        category: 'Organic Products',
        brand: 'Dharti Ratna Organic',
        price: 450,
        originalPrice: 550,
        discountPercentage: 18,
        rating: 4.7,
        reviewsCount: 65,
        image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 300,
        unit: '50 kg HDPE bag',
        description: 'A-grade vermicompost enriched with Trichoderma and beneficial soil microbes. Restores soil humus and porosity.',
      },
      {
        name: 'Liquid Seaweed Bio-Stimulant (Kelp Extract)',
        category: 'Nutrients',
        brand: 'NutriKisan Bio',
        price: 520,
        originalPrice: 650,
        discountPercentage: 20,
        rating: 4.7,
        reviewsCount: 22,
        image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 90,
        unit: '500 ml bottle',
        description: 'Enriched with natural auxins, cytokinins, and micro-minerals. Promotes root proliferation and stress resilience.',
      },
      {
        name: 'Heavy Duty Drip Lateral Pipe (16mm, Class 2)',
        category: 'Irrigation',
        brand: 'Finolex Plastro',
        price: 1850,
        originalPrice: 2200,
        discountPercentage: 16,
        rating: 4.8,
        reviewsCount: 44,
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 80,
        unit: '400 meters bundle',
        description: 'Virgin polymer UV stabilized lateral tube with 40cm emitter spacing (2 LPH discharge). Certified ISI standard.',
      },
      {
        name: 'Zinc Sulphate Heptahydrate (21% Zn)',
        category: 'Fertilizers',
        brand: 'GSFC Agri Products',
        price: 750,
        originalPrice: 850,
        discountPercentage: 12,
        rating: 4.6,
        reviewsCount: 29,
        image: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 110,
        unit: '10 kg bag',
        description: 'Essential micronutrient for overcoming Khaira disease in paddy and white bud deficiency in maize.',
      },
      {
        name: 'Trichoderma Viride Bio-Fungicide (1% WP)',
        category: 'Pest Control',
        brand: 'Krishi Rakshak Bio',
        price: 340,
        originalPrice: 420,
        discountPercentage: 19,
        rating: 4.9,
        reviewsCount: 51,
        image: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 140,
        unit: '1 kg packet',
        description: 'Natural antagonistic fungus that protects crops against root rot, collar rot, wilt, and damping-off.',
      },
      {
        name: 'Mini Power Tiller 7HP Petrol Engine',
        category: 'Machinery',
        brand: 'Kirloskar Kisan',
        price: 38500,
        originalPrice: 45000,
        discountPercentage: 14,
        rating: 4.9,
        reviewsCount: 16,
        image: 'https://images.unsplash.com/photo-1590682680695-43b964a3ae17?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 10,
        unit: '1 Machine with Rotary Blades',
        description: 'Powerful 4-stroke air-cooled engine ideal for inter-cultivation, weeding in cotton, sugarcane, and orchards.',
      },
      {
        name: 'Ergonomic Telescopic Fruit Picker & Pruner',
        category: 'Tools',
        brand: 'Falcon Garden Tools',
        price: 1350,
        originalPrice: 1650,
        discountPercentage: 18,
        rating: 4.5,
        reviewsCount: 18,
        image: 'https://images.unsplash.com/photo-1590682680695-43b964a3ae17?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 45,
        unit: '1 Piece (Extends to 10 feet)',
        description: 'High-carbon steel bypass blade with lightweight aluminum pole for effortless mango, citrus, and guava harvesting.',
      },
      {
        name: 'Organic Neem Cake Fertilizer Powder',
        category: 'Organic Products',
        brand: 'Dharti Ratna Organic',
        price: 850,
        originalPrice: 980,
        discountPercentage: 13,
        rating: 4.8,
        reviewsCount: 37,
        image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 160,
        unit: '25 kg bag',
        description: 'Residual neem cake after cold extraction. Acts as a slow-release natural nitrogen source and nematicide.',
      },
      {
        name: 'Chelated Micronutrient Mixture (Grade 4)',
        category: 'Nutrients',
        brand: 'Aries Agro Chem',
        price: 490,
        originalPrice: 580,
        discountPercentage: 15,
        rating: 4.7,
        reviewsCount: 40,
        image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 75,
        unit: '1 kg pouch',
        description: 'Contains EDTA chelated Fe, Mn, Zn, Cu with Boron & Mo. Completely soluble and rapid cure for leaf chlorosis.',
      },
      {
        name: 'Venturi Fertilizer Injector (1.5 inch)',
        category: 'Irrigation',
        brand: 'Netafim Flow Systems',
        price: 950,
        originalPrice: 1200,
        discountPercentage: 21,
        rating: 4.6,
        reviewsCount: 23,
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 50,
        unit: '1 Injector with Suction Tube',
        description: 'Precision chemical-resistant venturi tube for uniform injection of soluble liquid fertilizers into drip networks.',
      },
      {
        name: 'Pheromone Trap for Pink Bollworm (Set of 5)',
        category: 'Pest Control',
        brand: 'Krishi Rakshak Bio',
        price: 420,
        originalPrice: 520,
        discountPercentage: 19,
        rating: 4.8,
        reviewsCount: 62,
        image: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 210,
        unit: '5 Funnel Traps + 5 Lures',
        description: 'Lure attracts adult male moths to break reproduction cycles without synthetic pesticides.',
      },
      {
        name: 'Hybrid Tomato Seeds (Abhinav F1)',
        category: 'Seeds',
        brand: 'Syngenta Seeds India',
        price: 980,
        originalPrice: 1150,
        discountPercentage: 15,
        rating: 4.9,
        reviewsCount: 48,
        image: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb22510?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 95,
        unit: '10g packet (~3,000 seeds)',
        description: 'Determinate vigorously branching hybrid with exceptional firmness and deep red colour. Tolerant to TYLCV.',
      },
      {
        name: 'Heavy Duty Stainless Steel Hand Weeder',
        category: 'Tools',
        brand: 'Kisan Craft India',
        price: 320,
        originalPrice: 399,
        discountPercentage: 20,
        rating: 4.5,
        reviewsCount: 27,
        image: 'https://images.unsplash.com/photo-1590682680695-43b964a3ae17?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 180,
        unit: '1 Tool with Comfort Grip',
        description: 'V-notch forged weed extractor designed to remove tap-rooted weeds without disturbing adjacent seedlings.',
      },
      {
        name: 'Potassium Schoenite (K2O 23% + MgO 11%)',
        category: 'Fertilizers',
        brand: 'IFFCO Agro Tech',
        price: 1350,
        originalPrice: 1500,
        discountPercentage: 10,
        rating: 4.8,
        reviewsCount: 19,
        image: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&q=80&w=400',
        inStock: true,
        stockQuantity: 65,
        unit: '25 kg bag',
        description: 'Double sulphate of potassium and magnesium. Low chloride content makes it ideal for salt-sensitive crops.',
      },
    ]);
    console.log('✅ Seeded 20 Products');

    // 8. Seed 10 Government Schemes
    await Scheme.insertMany([
      {
        title: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
        category: 'Financial Support',
        description: 'Central sector scheme providing income support of ₹6,000 per year in three equal installments to all landholding farmer families.',
        eligibility: [
          'All landholding farmer families with cultivable land in their names.',
          'Subject to exclusion criteria for higher income bracket individuals.',
          'Aadhaar-seeded active bank account required.',
        ],
        benefits: '₹6,000 per year transferred directly to bank account via DBT in 3 installments of ₹2,000.',
        documents: ['Aadhaar Card', 'Land ownership document (7/12 or 8A extract)', 'Active Bank Passbook'],
        deadline: 'Ongoing / Open Year-Round',
        applicationLink: 'https://pmkisan.gov.in',
        applicableStates: ['All India'],
        minLandArea: 0.1,
        maxLandArea: 50,
        featured: true,
      },
      {
        title: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
        category: 'Crop Insurance',
        description: 'Comprehensive financial protection against non-preventable natural risks from pre-sowing to post-harvest stages for notified crops.',
        eligibility: [
          'All farmers growing notified crops in notified areas including sharecroppers and tenant farmers.',
          'Mandatory for loanee farmers availing crop loans, optional for non-loanees.',
        ],
        benefits: 'Insurance cover with maximum premium of only 2% for Kharif, 1.5% for Rabi, and 5% for horticultural/commercial crops.',
        documents: ['Kisan Credit Card (KCC) details', 'Sowing Certificate / V-Form', 'Land Title Document'],
        deadline: 'Before 31st July (Kharif) / 31st December (Rabi)',
        applicationLink: 'https://pmfby.gov.in',
        applicableStates: ['All India'],
        minLandArea: 0.1,
        maxLandArea: 100,
        featured: true,
      },
      {
        title: 'Micro Irrigation Subsidy (Per Drop More Crop - PMKSY)',
        category: 'Irrigation',
        description: 'Financial assistance for installing drip and sprinkler systems to improve farm water use efficiency and crop productivity.',
        eligibility: [
          'Small and marginal farmers receive up to 70% subsidy; general farmers receive up to 55% subsidy.',
          'Must have assured water source on the designated farm plot.',
        ],
        benefits: 'Up to 70% direct government subsidy on the benchmark cost of drip/sprinkler systems.',
        documents: ['7/12 & 8A land records', 'Water source verification certificate', 'Electricity connection / solar pump proof'],
        deadline: 'Open all year via state portals (e.g. GGRC in Gujarat)',
        applicationLink: 'https://pmksy.gov.in',
        applicableStates: ['All India', 'Gujarat', 'Maharashtra', 'Rajasthan'],
        minLandArea: 0.5,
        maxLandArea: 12.5,
        featured: true,
      },
      {
        title: 'Soil Health Card Scheme (SHC)',
        category: 'Soil Health',
        description: 'Provides customized soil nutrient status reports and dosage recommendations for 12 essential nutrients every 2 years.',
        eligibility: ['All agricultural landholders in rural districts.'],
        benefits: 'Free testing of 12 chemical and physical soil parameters plus tailored fertilizer recommendations.',
        documents: ['Farmer Aadhaar Card', 'GPS Coordinates of field plot'],
        deadline: 'Continuous cyclic coverage',
        applicationLink: 'https://soilhealth.dac.gov.in',
        applicableStates: ['All India'],
        minLandArea: 0,
        maxLandArea: 100,
        featured: false,
      },
      {
        title: 'Agricultural Mechanization Promotion Subsidy (SMAM)',
        category: 'Equipment Subsidy',
        description: 'Subsidies for procurement of agricultural tractors, power tillers, rotavators, sprayers, and combine harvesters.',
        eligibility: [
          'Individual farmers, self-help groups, and farmer producer organizations (FPOs).',
          'Women farmers and SC/ST farmers receive higher slab subsidies (up to 50%).',
        ],
        benefits: '40% to 50% capital subsidy on verified machinery equipment purchase.',
        documents: ['Valid Quotation from authorized dealer', 'Aadhaar Card', 'Land ownership proof', 'Caste certificate (if applicable)'],
        deadline: 'Annual district allocation windows',
        applicationLink: 'https://agrimachinery.nic.in',
        applicableStates: ['All India', 'Gujarat'],
        minLandArea: 1.0,
        maxLandArea: 50,
        featured: false,
      },
      {
        title: 'Paramparagat Krishi Vikas Yojana (PKVY)',
        category: 'Organic Farming',
        description: 'Financial support of ₹50,000 per hectare over 3 years for organic farming cluster adoption, PGS certification, and bio-inputs.',
        eligibility: ['Farmers willing to form clusters of 20 or more farmers covering at least 50 acres.'],
        benefits: '₹31,000/ha incentive directly for on-farm organic inputs, plus free PGS organic certification and branding.',
        documents: ['Farmer Cluster Registration Agreement', 'Bank Account details', 'Land possession records'],
        deadline: 'Phase-wise cluster onboarding',
        applicationLink: 'https://pgsindia-ncof.gov.in',
        applicableStates: ['All India'],
        minLandArea: 0.5,
        maxLandArea: 25,
        featured: false,
      },
      {
        title: 'Kisan Credit Card (KCC) concessional loan',
        category: 'Financial Support',
        description: 'Short-term credit facility for cultivation expenses and post-harvest maintenance at an effective concessional interest rate of 4%.',
        eligibility: ['All farmers including individual cultivators, joint liability groups, and sharecroppers.'],
        benefits: 'Collateral-free loan up to ₹1.60 Lakh (or up to ₹3.00 Lakh with interest subvention at 4%).',
        documents: ['Land Records', 'Passport Photo', 'KYC Documents'],
        deadline: 'Ongoing at all rural bank branches',
        applicationLink: 'https://myscheme.gov.in',
        applicableStates: ['All India'],
        minLandArea: 0.1,
        maxLandArea: 100,
        featured: false,
      },
      {
        title: 'Pradhan Mantri Krishi Sinchayee Yojana - Watershed (PMKSY-WDC)',
        category: 'Irrigation',
        description: 'Community rainwater harvesting structures, farm ponds, check dams, and contour bunding to recharge groundwater tables.',
        eligibility: ['Farmers in rainfed and semi-arid drought-prone blocks.'],
        benefits: 'Up to 100% grant for community check dams and 50% subsidy for individual farm ponds (Khet Talavadi).',
        documents: ['Gram Panchayat NOC', '7/12 Land extract'],
        deadline: 'Village Gram Sabha planning sessions',
        applicationLink: 'https://pmksy.gov.in',
        applicableStates: ['All India', 'Gujarat'],
        minLandArea: 1.0,
        maxLandArea: 100,
        featured: false,
      },
      {
        title: 'Sub-Mission on Seeds and Planting Material (SMSP)',
        category: 'Equipment Subsidy',
        description: 'Subsidy on high-yielding foundation and certified seed varieties for small and marginal farmers.',
        eligibility: ['Small and marginal farmers holding up to 2 hectares.'],
        benefits: 'Up to 50% subsidy on seed mini-kits and foundation seed packages.',
        documents: ['Small farmer certificate from Talati', 'Aadhaar Card'],
        deadline: 'Prior to Kharif / Rabi sowing dates',
        applicationLink: 'https://seednet.gov.in',
        applicableStates: ['All India'],
        minLandArea: 0.1,
        maxLandArea: 5.0,
        featured: false,
      },
      {
        title: 'Solar Agriculture Pump Subsidy (PM-KUSUM Component B)',
        category: 'Equipment Subsidy',
        description: 'Installation of standalone solar agriculture pumps with 60% combined central and state government subsidy.',
        eligibility: ['Farmers having cultivated land without existing grid electricity pump connection.'],
        benefits: 'Up to 60% subsidy (30% Centre + 30% State); farmer pays only 10% cash with 30% bank loan.',
        documents: ['Electricity Board Non-connection certificate', 'Aadhaar Card', 'Land 7/12 extract'],
        deadline: 'State Discom portal release windows',
        applicationLink: 'https://pmkusum.mnre.gov.in',
        applicableStates: ['All India', 'Gujarat', 'Rajasthan'],
        minLandArea: 1.0,
        maxLandArea: 25,
        featured: true,
      },
    ]);
    console.log('✅ Seeded 10 Government Schemes');

    // 9. Seed 5 Experts
    const experts = await Expert.insertMany([
      {
        name: 'Dr. Anand Patel',
        title: 'Senior Principal Scientist & Crop Specialist',
        specialization: 'Crop Specialist',
        rating: 4.9,
        reviewsCount: 112,
        experienceYears: 18,
        qualification: 'Ph.D. in Agronomy, Anand Agricultural University (AAU)',
        avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=300',
        languages: ['English', 'Gujarati', 'Hindi'],
        isAvailable: true,
        consultationsDone: 480,
        bio: 'Over 18 years pioneering integrated crop management for cotton, groundnut, and wheat across western India.',
      },
      {
        name: 'Dr. Meera Shah',
        title: 'Director of Soil Science & Agro-Chemistry',
        specialization: 'Soil Specialist',
        rating: 4.8,
        reviewsCount: 89,
        experienceYears: 14,
        qualification: 'Ph.D. in Soil Science, IARI New Delhi',
        avatar: 'https://images.unsplash.com/photo-1594824813589-2f22bdf55f60?auto=format&fit=crop&q=80&w=300',
        languages: ['English', 'Gujarati', 'Hindi'],
        isAvailable: true,
        consultationsDone: 360,
        bio: 'Specialist in soil microbial revitalization, salinity remediation, and precision balanced NPK-micronutrient protocols.',
      },
      {
        name: 'Dr. Rajesh Mehta',
        title: 'Chief Agrometeorology & Irrigation Engineer',
        specialization: 'Irrigation Expert',
        rating: 4.7,
        reviewsCount: 76,
        experienceYears: 16,
        qualification: 'M.Tech & Ph.D. in Water Resources & Precision Irrigation, IIT Kharagpur',
        avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=300',
        languages: ['English', 'Hindi', 'Gujarati'],
        isAvailable: true,
        consultationsDone: 295,
        bio: 'Designed automated IoT micro-drip networks spanning 12,000+ acres across drought-prone regions in Gujarat and Rajasthan.',
      },
      {
        name: 'Dr. Sunita Varma',
        title: 'Associate Professor of Plant Pathology & Entomology',
        specialization: 'Pest Specialist',
        rating: 4.9,
        reviewsCount: 94,
        experienceYears: 12,
        qualification: 'Ph.D. in Entomology, Junagadh Agricultural University (JAU)',
        avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=300',
        languages: ['English', 'Hindi', 'Gujarati'],
        isAvailable: true,
        consultationsDone: 410,
        bio: 'Expert in biological control systems, pheromone monitoring, and managing invasive pests without harmful residues.',
      },
      {
        name: 'Er. Vikram Desai',
        title: 'Agricultural Mechanization & Precision Farming Advisor',
        specialization: 'Machinery Specialist',
        rating: 4.8,
        reviewsCount: 63,
        experienceYears: 11,
        qualification: 'M.Tech in Farm Machinery & Power, CIAE Bhopal',
        avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=300',
        languages: ['English', 'Gujarati', 'Hindi'],
        isAvailable: true,
        consultationsDone: 215,
        bio: 'Advises farmers on custom hiring centers, solar pumps, drone sprayers, and farm mechanization economics.',
      },
    ]);
    console.log('✅ Seeded 5 Experts');

    // 10. Seed Consultations
    await Consultation.insertMany([
      {
        userId: farmer1._id,
        expertId: experts[0]._id,
        problemTitle: 'Yellow spots appearing on lower leaves of Bt Cotton',
        category: 'Crop',
        crop: 'Cotton',
        description: 'Noticed small circular lesions with red borders starting from bottom canopy. Soil moisture is normal.',
        status: 'Answered',
        expertReply: {
          expertName: 'Dr. Anand Patel',
          advice: 'The symptoms are consistent with Cercospora leaf spot. Avoid overhead sprinkling, remove infected bottom leaves to improve air circulation, and spray Mancozeb 75% WP @ 2.5 g/L.',
          suggestedTreatment: 'Mancozeb 75% WP + Bio-stimulant spray after morning dew clears.',
          repliedAt: new Date(),
        },
      },
      {
        userId: farmer3._id,
        expertId: experts[1]._id,
        problemTitle: 'Soil crusting and poor water penetration in Gondal plot',
        category: 'Soil',
        crop: 'Groundnut',
        description: 'After irrigation, the top layer turns hard and forms cracks, which hinders peg formation.',
        status: 'Answered',
        expertReply: {
          expertName: 'Dr. Meera Shah',
          advice: 'This is due to high sodium saturation and low organic matter in heavy black soil. Apply agricultural gypsum @ 250 kg/acre and incorporate 4 tonnes of vermicompost during land preparation.',
          suggestedTreatment: 'Agricultural Gypsum + Farmyard Manure mulch.',
          repliedAt: new Date(),
        },
      },
    ]);

    // 11. Seed 10 Knowledge Articles
    await Article.insertMany([
      {
        title: '5 Ways to Improve Soil Health and Long-Term Crop Yields',
        slug: '5-ways-to-improve-soil-health-and-yields',
        category: 'Soil Health',
        author: 'Dr. Meera Shah',
        authorTitle: 'Director of Soil Science, Krishi Digital Research',
        summary: 'Actionable techniques for Indian farmers to boost organic carbon, retain soil moisture, and balance micronutrients naturally.',
        content: `Soil is the foundation of agricultural prosperity. In many intensive farming belts of India, continuous chemical fertilizer use has depleted soil organic carbon below the crucial threshold of 0.75%.

Here are five proven, scientifically verified practices to restore soil fertility:

1. Regular Organic Carbon Enrichment: Add 4-5 tonnes of well-rotted Farmyard Manure (FYM) or 2 tonnes of vermicompost per acre annually.
2. Green Manuring in Crop Rotation: Cultivate fast-growing leguminous crops like Sunhemp or Dhaincha for 45 days and plough them into the soil just before flowering.
3. Residue Mulching Instead of Stubble Burning: Leaving crop residue on the soil surface reduces moisture evaporation by up to 35% and feeds earthworms.
4. Precision Balanced Fertilization Based on Soil Testing: Avoid excessive urea (N) and DAP (P). Always follow the 4R Nutrient Stewardship principle (Right source, Right rate, Right time, Right place).
5. Bio-Fertilizer Inoculation: Seed treatment with Rhizobium, Azotobacter, and PSB (Phosphate Solubilizing Bacteria) activates native soil nutrients efficiently.`,
        readTime: '4 min read',
        viewsCount: 342,
        featured: true,
        image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&q=80&w=600',
        tags: ['Soil Health', 'Organic Farming', 'Fertilizer'],
      },
      {
        title: 'Best Irrigation Practices for Cotton: Saving Water and Maximizing Bolls',
        slug: 'best-irrigation-practices-for-cotton',
        category: 'Water Management',
        author: 'Dr. Rajesh Mehta',
        authorTitle: 'Irrigation & Water Resources Specialist',
        summary: 'Learn how to synchronize drip irrigation schedules with critical physiological stages of cotton plants for up to 30% yield boost.',
        content: `Cotton is a sensitive crop where both water excess and water stress can trigger massive shedding of squares and flower bolls.

Critical Growth Stages for Irrigation:
- Germination to Vegetative Phase: Minimal moisture needed; over-irrigation promotes vegetative lankiness instead of root penetration.
- Squaring and Flowering Stage (Day 45 to 80): Critical stage. Soil moisture must remain above 55%.
- Boll Development Stage (Day 80 to 120): Peak water demand. Drip fertigation with Potassium Nitrate is vital.
- Boll Bursting & Maturity (Day 120 onwards): Gradually taper off water to ensure clean, stain-free lint.

Adopting automated inline drip systems saves up to 45% water compared to conventional flood methods while doubling fertilizer efficiency.`,
        readTime: '5 min read',
        viewsCount: 280,
        featured: true,
        image: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb22510?auto=format&fit=crop&q=80&w=600',
        tags: ['Cotton', 'Drip Irrigation', 'Water Conservation'],
      },
      {
        title: 'Modern Farming Techniques: Drones, IoT Sensors, and Digital Mandis',
        slug: 'modern-farming-techniques-drones-sensors-mandis',
        category: 'Modern Farming',
        author: 'Er. Vikram Desai',
        authorTitle: 'Precision Agriculture Engineer',
        summary: 'Explore how Indian agriculture is transforming with AI-driven multispectral scouting, smart solenoid valves, and electronic APMC market linkage.',
        content: `The modern Indian farmer is no longer reliant on guesswork. With affordable IoT sensors, satellite imagery, and mobile apps, farming is evolving into a high-precision science.

Key Innovations:
- Drone-based Ultra Low Volume (ULV) Spraying: Covers an entire acre in under 7 minutes with 90% water reduction.
- Real-time Capacitive Soil Sensors: Transmit moisture and temperature data to the farmer's phone, automating pump operations.
- Electronic Price Transparency: Mandi tracking platforms empower farmers to negotiate fair prices instead of distress selling.`,
        readTime: '6 min read',
        viewsCount: 415,
        featured: false,
        image: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&q=80&w=600',
        tags: ['Technology', 'IoT', 'Drones', 'Smart Farming'],
      },
      {
        title: 'How to Identify and Treat Common Crop Diseases Early',
        slug: 'how-to-identify-and-treat-common-crop-diseases',
        category: 'Pest Management',
        author: 'Dr. Sunita Varma',
        authorTitle: 'Plant Pathologist',
        summary: 'A visual field diagnostic guide for spotting leaf spots, powdery mildew, rusts, and bacterial blights before severe damage occurs.',
        content: `Early identification is 90% of plant protection. Learn the diagnostic differences between fungal spots, bacterial ooze, and nutritional deficiencies to avoid unnecessary pesticide sprays.`,
        readTime: '5 min read',
        viewsCount: 390,
        featured: false,
        image: 'https://images.unsplash.com/photo-1599818816949-a29d5b4e7d69?auto=format&fit=crop&q=80&w=600',
        tags: ['Crop Doctor', 'Disease Control', 'Plant Health'],
      },
      {
        title: 'Complete Guide to Wheat Cultivation: Sowing, Nutrition, and Harvesting',
        slug: 'complete-guide-to-wheat-cultivation',
        category: 'Crop Guides',
        author: 'Dr. Anand Patel',
        authorTitle: 'Senior Agronomist',
        summary: 'Step-by-step agronomic roadmap for cultivating high-yield Sharbati and Lokwan wheat varieties in Central and Western India.',
        content: `Wheat is the backbone of India's food security. Timing the Crown Root Initiation (CRI) stage at 21 days after sowing determines the number of productive tillers per plant.`,
        readTime: '7 min read',
        viewsCount: 520,
        featured: false,
        image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=600',
        tags: ['Wheat', 'Kharif', 'Rabi', 'Crop Management'],
      },
      {
        title: 'Transitioning to Certified Organic Farming: Pitfalls and Solutions',
        slug: 'transitioning-to-certified-organic-farming',
        category: 'Organic Farming',
        author: 'Dr. Meera Shah',
        authorTitle: 'Organic Extension Specialist',
        summary: 'Navigating the 3-year conversion period, PGS India certification requirements, and maintaining yields with biological inputs.',
        content: `Transitioning from chemical to organic agriculture requires patience. Building soil biological capacity takes 24-36 months. Using Jeevamrut, Panchagavya, and green manure ensures yields do not crash during the transition.`,
        readTime: '6 min read',
        viewsCount: 260,
        featured: false,
        image: 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&q=80&w=600',
        tags: ['Organic', 'Bio-fertilizer', 'Certification'],
      },
      {
        title: 'Government Subsidies for Solar Pumps and Farm Machinery Explained',
        slug: 'government-subsidies-solar-pumps-machinery-explained',
        category: 'Government Updates',
        author: 'Er. Vikram Desai',
        authorTitle: 'Agri Policy Analyst',
        summary: 'How to claim up to 60% capital subsidies under PM-KUSUM and SMAM portals with minimal paperwork.',
        content: `Solar energy gives farmers free daytime electricity for irrigation. Learn how to verify your land documents, obtain dealer quotes, and track subsidy approval via state agricultural portals.`,
        readTime: '4 min read',
        viewsCount: 610,
        featured: true,
        image: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&q=80&w=600',
        tags: ['PM-KUSUM', 'Solar Pump', 'Subsidies'],
      },
      {
        title: 'Integrated Pest Management (IPM) for Sucking Pests in Cotton',
        slug: 'integrated-pest-management-for-cotton-pests',
        category: 'Pest Management',
        author: 'Dr. Sunita Varma',
        authorTitle: 'Entomologist',
        summary: 'Controlling whiteflies, jassids, and thrips with yellow sticky traps, neem extracts, and minimal chemical intervention.',
        content: `Indiscriminate chemical sprays kill beneficial natural predators like ladybird beetles and chrysoperla. An IPM approach preserves natural enemies while keeping pest populations below economic threshold levels.`,
        readTime: '5 min read',
        viewsCount: 310,
        featured: false,
        image: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&q=80&w=600',
        tags: ['IPM', 'Cotton', 'Biocontrol'],
      },
      {
        title: 'Water Harvesting via Farm Ponds: Drought-Proofing Your Field',
        slug: 'water-harvesting-via-farm-ponds',
        category: 'Water Management',
        author: 'Dr. Rajesh Mehta',
        authorTitle: 'Hydrologist',
        summary: 'Engineering small farm ponds (Khet Talavadi) to store monsoon runoff and recharge localized groundwater wells.',
        content: `A 30m x 30m x 3m farm pond lined with HDPE membrane can store over 2.5 million litres of water, enough to provide two life-saving irrigations during dry spells.`,
        readTime: '5 min read',
        viewsCount: 220,
        featured: false,
        image: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?auto=format&fit=crop&q=80&w=600',
        tags: ['Farm Pond', 'Rainwater Harvesting', 'Irrigation'],
      },
      {
        title: 'Maximizing Groundnut Production in Saurashtra Sandy Loam',
        slug: 'maximizing-groundnut-production-saurashtra',
        category: 'Crop Guides',
        author: 'Dr. Anand Patel',
        authorTitle: 'Oilseed Specialist',
        summary: 'Key agronomic interventions from gypsum application at pegging to controlling collar rot and tikka leaf disease.',
        content: `Groundnut requires high calcium for pod filling. Applying 250 kg/acre gypsum at 45 days after sowing prevents 'pops' (empty pods) and substantially boosts oil content.`,
        readTime: '6 min read',
        viewsCount: 340,
        featured: false,
        image: 'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&q=80&w=600',
        tags: ['Groundnut', 'Oilseed', 'Saurashtra'],
      },
    ]);
    console.log('✅ Seeded 10 Articles');

    // 12. Seed 10 Notifications
    await Notification.insertMany([
      {
        userId: farmer1._id,
        title: '⚠️ Heavy rain expected tomorrow.',
        message: 'Weather forecast warns of scattered heavy showers. Ensure proper field drainage in Cotton plots.',
        type: 'weather',
        link: '/weather',
        isRead: false,
      },
      {
        userId: farmer1._id,
        title: '🌱 Fertilization recommended for Cotton.',
        message: 'Your Bt Cotton crop is at flowering stage. Apply water-soluble 0:52:34 foliar spray.',
        type: 'crop',
        link: '/crops',
        isRead: false,
      },
      {
        userId: farmer1._id,
        title: '📈 Cotton price increased by 4.2%.',
        message: 'Modal rate in Ahmedabad APMC reached ₹7,200/Q today.',
        type: 'market',
        link: '/market',
        isRead: false,
      },
      {
        userId: farmer1._id,
        title: '💧 Irrigation recommended tomorrow morning.',
        message: 'Sensor indicates Zone A moisture has dipped to 32%. Recommended: 1,200 Litres at 6:00 AM.',
        type: 'irrigation',
        link: '/irrigation',
        isRead: false,
      },
      {
        userId: farmer1._id,
        title: '🏛️ New Scheme: PMKSY Drip Subsidy Window Open',
        message: 'Applications for 70% micro-irrigation subsidy are now open on the portal.',
        type: 'scheme',
        link: '/schemes',
        isRead: true,
      },
      {
        userId: farmer2._id,
        title: '🌾 Wheat First Top-Dressing Reminder',
        message: 'GW-496 crop is 25 days old. Apply neem-coated urea before next scheduled watering.',
        type: 'crop',
        link: '/crops',
        isRead: false,
      },
      {
        userId: farmer3._id,
        title: '🥜 Groundnut Pegging Stage Alert',
        message: 'Apply gypsum @ 200 kg/acre to ensure healthy pod formation and avoid empty shells.',
        type: 'crop',
        link: '/crops',
        isRead: false,
      },
      {
        userId: farmer3._id,
        title: '📈 Jeera Prices Surge at Unjha APMC',
        message: 'Unjha Mandi recorded an all-time seasonal high of ₹26,800/Q for Grade A cumin.',
        type: 'market',
        link: '/market',
        isRead: true,
      },
      {
        userId: farmer4._id,
        title: '📦 Order #KD-ORD-2026-8192 Shipped',
        message: 'Your order of Battery Knapsack Sprayer has departed the regional fulfillment center.',
        type: 'order',
        link: '/orders',
        isRead: false,
      },
      {
        userId: farmer5._id,
        title: '👨‍🔬 Advisory Query Response Available',
        message: 'Dr. Anand Patel has submitted answers to your query regarding basmati paddy blast.',
        type: 'expert',
        link: '/experts',
        isRead: false,
      },
    ]);
    console.log('✅ Seeded 10 Notifications');

    // 13. Seed 10 Irrigation Records
    await Irrigation.insertMany([
      {
        userId: farmer1._id,
        farmId: farms[0]._id,
        farmName: 'Surya Green Farm - Field 1',
        zoneName: 'Zone A - Main Cotton Field',
        soilMoisture: 32,
        requiredMoisture: 55,
        status: 'Irrigation Required',
        waterAmountLitres: 1200,
        scheduledTime: '6:00 AM – 8:00 AM',
        sensors: {
          soilMoisture: 32,
          temperature: 29,
          humidity: 58,
          waterTankLevel: 78,
          flowRate: 24,
        },
        historyData: [
          { time: '00:00', moisture: 38 },
          { time: '04:00', moisture: 36 },
          { time: '08:00', moisture: 35 },
          { time: '12:00', moisture: 33 },
          { time: '16:00', moisture: 32 },
          { time: '20:00', moisture: 32 },
          { time: 'Now', moisture: 32 },
        ],
      },
      {
        userId: farmer1._id,
        farmId: farms[0]._id,
        farmName: 'Surya Green Farm - Field 1',
        zoneName: 'Zone B - Tomato Greenhouse',
        soilMoisture: 58,
        requiredMoisture: 60,
        status: 'Normal',
        waterAmountLitres: 400,
        scheduledTime: '5:30 AM – 6:30 AM',
        sensors: {
          soilMoisture: 58,
          temperature: 27,
          humidity: 65,
          waterTankLevel: 78,
          flowRate: 15,
        },
        historyData: [
          { time: '04:00', moisture: 54 },
          { time: '08:00', moisture: 62 },
          { time: '12:00', moisture: 60 },
          { time: '16:00', moisture: 58 },
        ],
      },
      {
        userId: farmer1._id,
        farmId: farms[1]._id,
        farmName: 'Sardar Agro Plot - Field 2',
        zoneName: 'Plot 1 - Young Wheat',
        soilMoisture: 42,
        requiredMoisture: 50,
        status: 'Normal',
        waterAmountLitres: 800,
        scheduledTime: '7:00 AM – 9:00 AM',
        sensors: {
          soilMoisture: 42,
          temperature: 28,
          humidity: 60,
          waterTankLevel: 85,
          flowRate: 20,
        },
        historyData: [
          { time: '06:00', moisture: 45 },
          { time: '12:00', moisture: 43 },
          { time: '18:00', moisture: 42 },
        ],
      },
      {
        userId: farmer2._id,
        farmId: farms[2]._id,
        farmName: 'Shree Krishna Farm',
        zoneName: 'North Acre - Sharbati Wheat',
        soilMoisture: 30,
        requiredMoisture: 52,
        status: 'Irrigation Required',
        waterAmountLitres: 1400,
        scheduledTime: '6:00 AM – 8:30 AM',
        sensors: {
          soilMoisture: 30,
          temperature: 30,
          humidity: 55,
          waterTankLevel: 92,
          flowRate: 28,
        },
        historyData: [
          { time: '00:00', moisture: 35 },
          { time: '08:00', moisture: 33 },
          { time: '16:00', moisture: 30 },
        ],
      },
      {
        userId: farmer3._id,
        farmId: farms[3]._id,
        farmName: 'Gondal Golden Acres',
        zoneName: 'East Field - Groundnut Pegging',
        soilMoisture: 52,
        requiredMoisture: 55,
        status: 'Normal',
        waterAmountLitres: 1600,
        scheduledTime: '5:00 AM – 7:30 AM',
        sensors: {
          soilMoisture: 52,
          temperature: 29,
          humidity: 64,
          waterTankLevel: 70,
          flowRate: 32,
        },
        historyData: [
          { time: '06:00', moisture: 54 },
          { time: '12:00', moisture: 53 },
          { time: '18:00', moisture: 52 },
        ],
      },
      {
        userId: farmer3._id,
        farmId: farms[3]._id,
        farmName: 'Gondal Golden Acres',
        zoneName: 'West Field - Cotton Hy-6',
        soilMoisture: 28,
        requiredMoisture: 55,
        status: 'Irrigation Required',
        waterAmountLitres: 1500,
        scheduledTime: '6:30 AM – 9:00 AM',
        sensors: {
          soilMoisture: 28,
          temperature: 31,
          humidity: 50,
          waterTankLevel: 70,
          flowRate: 30,
        },
        historyData: [
          { time: '04:00', moisture: 32 },
          { time: '12:00', moisture: 29 },
          { time: '18:00', moisture: 28 },
        ],
      },
      {
        userId: farmer4._id,
        farmId: farms[5]._id,
        farmName: 'Gir Somnath Agro Vihar',
        zoneName: 'Sector 1 - GG-20 Groundnut',
        soilMoisture: 60,
        requiredMoisture: 55,
        status: 'Normal',
        waterAmountLitres: 900,
        scheduledTime: '6:00 AM – 7:30 AM',
        sensors: {
          soilMoisture: 60,
          temperature: 28,
          humidity: 72,
          waterTankLevel: 88,
          flowRate: 22,
        },
        historyData: [
          { time: '06:00', moisture: 64 },
          { time: '12:00', moisture: 62 },
          { time: '18:00', moisture: 60 },
        ],
      },
      {
        userId: farmer5._id,
        farmId: farms[6]._id,
        farmName: 'Narmada Valley Field',
        zoneName: 'Canal Basin - Basmati Paddy',
        soilMoisture: 75,
        requiredMoisture: 70,
        status: 'Normal',
        waterAmountLitres: 2400,
        scheduledTime: '5:00 AM – 8:00 AM',
        sensors: {
          soilMoisture: 75,
          temperature: 29,
          humidity: 78,
          waterTankLevel: 95,
          flowRate: 40,
        },
        historyData: [
          { time: '06:00', moisture: 80 },
          { time: '12:00', moisture: 77 },
          { time: '18:00', moisture: 75 },
        ],
      },
      {
        userId: farmer5._id,
        farmId: farms[7]._id,
        farmName: 'Padra Organic Greens',
        zoneName: 'Plot Alpha - Heirloom Tomato',
        soilMoisture: 48,
        requiredMoisture: 55,
        status: 'Normal',
        waterAmountLitres: 600,
        scheduledTime: '6:30 AM – 7:30 AM',
        sensors: {
          soilMoisture: 48,
          temperature: 27,
          humidity: 62,
          waterTankLevel: 65,
          flowRate: 18,
        },
        historyData: [
          { time: '06:00', moisture: 52 },
          { time: '12:00', moisture: 50 },
          { time: '18:00', moisture: 48 },
        ],
      },
      {
        userId: farmer2._id,
        farmId: farms[2]._id,
        farmName: 'Shree Krishna Farm',
        zoneName: 'South Acre - Kufri Potato',
        soilMoisture: 55,
        requiredMoisture: 58,
        status: 'Normal',
        waterAmountLitres: 750,
        scheduledTime: '6:00 AM – 7:15 AM',
        sensors: {
          soilMoisture: 55,
          temperature: 28,
          humidity: 59,
          waterTankLevel: 90,
          flowRate: 20,
        },
        historyData: [
          { time: '06:00', moisture: 58 },
          { time: '12:00', moisture: 56 },
          { time: '18:00', moisture: 55 },
        ],
      },
    ]);
    console.log('✅ Seeded 10 Irrigation Records');

    // 14. Seed Disease Reports
    await DiseaseReport.insertMany([
      {
        userId: farmer1._id,
        cropName: 'Cotton',
        diseaseName: 'Cercospora Leaf Spot',
        scientificName: 'Cercospora gossypina',
        severity: 'Medium',
        confidence: 89,
        imageUrl: 'https://images.unsplash.com/photo-1599818816949-a29d5b4e7d69?auto=format&fit=crop&q=80&w=400',
        symptoms: [
          'Circular brown spots with reddish margin',
          'Premature lower leaf shedding',
        ],
        recommendations: [
          'Remove infected leaves',
          'Improve field ventilation',
          'Monitor crop regularly',
          'Follow recommended treatment',
        ],
        chemicalControl: ['Mancozeb 75% WP @ 2.5 g/L'],
        organicControl: ['5% Neem Seed Kernel Extract (NSKE)'],
        isDemo: true,
      },
    ]);

    // 15. Seed Sample Orders
    const sampleProducts = await Product.find().limit(3);
    if (sampleProducts.length >= 2) {
      await Order.create({
        orderId: 'KD-ORD-2026-94812',
        userId: farmer1._id,
        items: [
          {
            productId: sampleProducts[0]._id,
            name: sampleProducts[0].name,
            price: sampleProducts[0].price,
            quantity: 2,
            image: sampleProducts[0].image,
            unit: sampleProducts[0].unit,
          },
          {
            productId: sampleProducts[1]._id,
            name: sampleProducts[1].name,
            price: sampleProducts[1].price,
            quantity: 1,
            image: sampleProducts[1].image,
            unit: sampleProducts[1].unit,
          },
        ],
        subtotal: (sampleProducts[0].price * 2) + sampleProducts[1].price,
        deliveryFee: 0,
        totalAmount: (sampleProducts[0].price * 2) + sampleProducts[1].price,
        paymentMethod: 'Kisan Pay / Cash on Delivery',
        paymentStatus: 'Paid',
        orderStatus: 'Shipped',
        shippingAddress: {
          fullName: 'Ramesh Patel',
          phone: '+91 98251 12345',
          village: 'Sanand',
          district: 'Ahmedabad',
          state: 'Gujarat',
          pincode: '382110',
          landmark: 'Near Gram Panchayat Office',
        },
        trackingUpdates: [
          { status: 'Confirmed', timestamp: new Date(Date.now() - 86400000 * 2), description: 'Order confirmed and verified.' },
          { status: 'Processing', timestamp: new Date(Date.now() - 86400000), description: 'Packed at Ahmedabad central warehouse.' },
          { status: 'Shipped', timestamp: new Date(), description: 'Out for rural delivery via Krishi Express.' },
        ],
      });
    }

    console.log('========================================================');
    console.log('🎉 SEED COMPLETED SUCCESSFULLY!');
    console.log('🔑 DEMO ADMIN CREDENTIALS (FOR DEVELOPMENT USE ONLY):');
    console.log('   Email:    admin@krishidigital.com');
    console.log('   Password: Admin@123');
    console.log('👨‍🌾 DEMO FARMER CREDENTIALS:');
    console.log('   Email:    ramesh.farmer@krishidigital.com');
    console.log('   Password: Farmer@123');
    console.log('========================================================');

    if (disconnectWhenDone) {
      await disconnectDB();
      process.exit(0);
    }
  } catch (error) {
    console.error('❌ Error during seeding:', error);
    if (disconnectWhenDone) {
      process.exit(1);
    }
  }
};

if (require.main === module || process.argv[1]?.includes('seed')) {
  runSeed(true);
}

